networks:
    jumpstart:
        driver: bridge

services:
    app:
        build:
            context: ..
            dockerfile: infra/app.dockerfile
        networks:
            - jumpstart


    nginx:
        build: nginx
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - jumpstart